print("ERES EL AMOR DE MI VIDA")
print("GRACIAS POR SIEMPRE APOYARME")
print("VAMOS A ECHARLE GANAS A ESTE PROYECTO QUE ES EL PRIMERO DE MUCHOS")
print("T E    A M O   M I L L O N E S")
print("Siempre estare a tu lado Rubens")